### ISSUE TITLE
E2BIG error on large input files / edl with MANY (+30000) lines

### ISSUE THREAD

**Issue by denjello** [denjello/VTT-Editor#8]
```
child_process.js:1155
    throw errnoException(err, 'spawn');
          ^
Error: spawn E2BIG
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1155:11)
    at exports.spawn (child_process.js:988:9)
    at Object.exports.execFile (child_process.js:682:15)
    at Object.exports.exec (child_process.js:642:18)
    at Transform.<anonymous> (/home/egal/GIT/VTT-Editor/edl_dropboring.js:200:28)
    at Transform.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at onEofChunk (_stream_readable.js:401:3)

```

**Comment by denjello** [comment]
This is the default from child process: `maxBuffer Number (Default: 200*1024)` which means a maximum buffer of 200 MB.

I raised it to 4000 MB and it "seemed" to work.

![testing](http://media.giphy.com/media/r7riLSvkCAgSI/giphy.gif)
